### ISSUE TITLE
web-optimition3-4

### ISSUE THREAD

**Issue by dlrandy** [dlrandy/note-issues#47]
优化css：
使用css的快捷属性；
使用shallow 选择器；
实践DRY原则；

web开发领域学习一个新的东西的时候，一定要先问有什么新的东西？有什么亮点？

优化css最基本的原则就是尽可能书写简洁(属性和选择器)的css

使用css的快捷方式意味着尽可能的最小冗余属性和值还有选择器。

css shorthand references：
https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

使用shallow css  selectors
shallow指的是css 选择器的特指性，当然也是指selector的层级要少一些（应该是只要能匹配到元素的最小部分）

保持css选择器简洁可以节省空间。减少复杂性，可以保持样式表的轻巧。

当你的选择器多于一或者两个元素的时候，就要考虑能否使用shallow selectors了。
有一个uncss可以移除未使用的css：
npm install -g uncss
uncss http://localhost:8080 -i  .modal.open > css/styles.css
查看这个url，只保留.modal.open.

使用css预编译器的时候，注意不要nest

DRY：css的同一属性和值不要经常出现在不同的selectors。
例如：
``` css
#main{
background:red;
}
#side{
background: red;
}
=====================
#main, #side{
background:red;
}
```
DRY的原则简单在于通过减少css里的冗余重复
可以使用csscss来减少css的冗余：
可以安装ruby，也可以安装node-sass，之后
gem install csscss
csscss styles.css -v --no-match-shorthand
这里的-v是verbose，显示出冗余的样式
--no-match-shorthand,显示不符合快捷方式的style
-v产出的都是可以共享的，然后在各个选择器里移除对应的属性和值。
有时候这个原则会产出相同的属性不同的值冗余的情况，这个通常发生在css里有手机和桌面断点的时候。对于响应式的网站最好的办法就是合并所有跨断点通用的值。

分段CSS：
就是把你的css划分到特定的页面模板；

当然把所有的css合并成一个文件，以至于用户第一次访问之后缓存，以至于后续的样式很快。但是这样对首次显示不好。比较好的做法就是机智的先加载几个可能访问的页面的css。这里的机智是指通过GA 查看behavior flow来决定的

如果使用了css框架的话，可以自定义框架的下载，当然你还可以进一步移出没有使用到的样式

==============================
使用惟一的页面模板分段css；

**Comment by dlrandy** [comment]
移动优先 就是 用户优先

以前是web一套手机一套，现在是响应式设计了

mobile-first desktop-first 是响应式设计的两个方法

两种方法都是以基本的CSS开始，这个CSS没有媒体查询并且定义的 是网站默认的样子

mobile-first网站一开始复杂性最小，复杂性会随着支持的设备到desktop增加


css手机优先的好处就是css专为那些手机设备准备的。手机设备不必须加在desktop样式，拦截媒体查询，然后再使用手机样式。

(X)em = (Y) px  / default font size(16);(x, y >= 1)
上面的默认size不一定是document的也有可能是父元素的。因为em上下文特定的

rem则总是相对document

``` css
//mobile first 的模板
/* css normalize/reset*/
//default size
html{
  font-size: 16px;
}
/*手机样式*/

@media screen and (min-width: 37.5em){
/* 600px /16px */
/*平板样式*/
}

@media screen  and (min-width: 62.5em) {
/* 1000px / 16px  */
/*桌面样式*/
}
```

在写响应式网站的时候，总是想使用通用的设备宽度，不要这样，要调出和你设计相关的断点宽度。
``` html
<meta name="viewport" content="width=device-width, initial-scale=1" >
这句是浏览器应该以设备的宽度来渲染页面。最初的页面缩放是100%。
```
网站花哨没毛病，但是慢就是大罪过了

从最小的开始，可以保证复杂的网站尽可能快地加载

google早在2015-4月的时候，搜索排名对手机友好的网站给于一定优先级

google判断手机友好的标准有两个是比较重要的：
配置正确的viewport；
响应性;（垂直滚动[或者水平滚动]）

手机友好测试工具
https://www.google.com/webmasters/tools/mobile-friendly/

**Comment by dlrandy** [comment]
除了写简洁手机友好的css，还要保证css有较高的执行性
相关的方法
1、普通的css避免使用@import
    因为这个并不会等待整个的样式表加载完毕后执行，所以他会增加页面的load time。
   同时它还会顺序化http request， 比如style.css里有@improt url(font.css), style.css 必须加载完，在加载 font.css。因为面向性能的网站是要尽可能的并发的 .serialize会增加页面的laod和渲染时间
2、link标签可以并发请求
    html被扫描之后，所有的link标签是同时加载的，最大一般是6个。lilnk在html下载的时候就会被扫描发现的。技术上来说在style里使用@import不会有性能问题的。但是在link或者css文件里 使用就会序列化请求的 
3、css文件是应该放在head里的
    好处是可以防止没有样式的内容的闪烁；提高加载的时候页面渲染得性能
4、防止没有加载到样式的内容闪烁
  也就是说不要让用户看到没有样式的内容。相看效果就把link放在body底部。因为刘浏览器是从上到下读取html的。解决的办法就是在head里使用link标签
5、提升页面的渲染性能
   这是因为如果较晚的加载css，浏览器就必须要re-render,repaint整个DOM 
6、使用更快的选择器(想选择前面的元素，select DOm4 !previous + next {}https://drafts.csswg.org/selectors-4/#subject)
   性能都差不多，（sibling 和伪类，Attr）相对慢一些 ，根据实际情况来选择。个人觉得合理使用唯一的选择器值
7、经可能的使用flexbox，box模型布局(float display margin padding)性能相对低
8、

**Comment by dlrandy** [comment]
css 的transition特别使用简单的线性的动画
transition: transition-property transition-duration transition-timing transition-delay;

原生css的几点好处：
广泛的北支持；
在回流复杂DOM的时候，CPU的使用更高效；
（因为在深度的DOM回流的时候，会减少thrashing[反复的beat],而且 没有脚本的开销）
没有开销；
(因为是浏览器自带的)。

css的transition有较高的动画性能，但是他们只是适合比较简单的情况。对于那些复杂的动画，还是要requestAnimationFrame的。


使用will-change来优化transiiton
当浏览器第一次执行transition的时候，他必须判断哪个属性要改变。这就导致一些额外的工作。
对于这种情况，可以使用translateZ创建一个新的栈环境，这个会提示浏览器css的动画应该由GPU 处理。但是这个只会告诉浏览器会有事发生，具体什么不知道。
而will-chnage 将会告诉浏览器哪个东东要变化。注意这个属性会影响设备的资源分配方式。千万不要使应用给所有的元素。还有需要给属性足够的时间起作用。
``` css
//下面这个就不好,因为浏览器没有时间应用优化
#siteHeader a:hover {
background-color: red;
will-change: background-color;
}
// better
#siteHeader:hover a {
will-change: background-color;
}
```
可以使用js动态添加will-change属性。注意用的时候加上用完之后要拿掉。
这个属性是预见那些事情发生而不是假设将会发生。

https://dev.opera.com/articles/css-will-change-property/
https://tympanus.net/codrops/css_reference/will-change/
https://stackoverflow.com/questions/26907265/css-will-change-how-to-use-it-how-it-works
https://www.sitepoint.com/introduction-css-will-change-property/
https://medium.com/zendesk-engineering/css-animation-optimisations-will-change-7e8ce3e63b81
https://medium.com/@benchaaben/css-the-will-change-property-fe63a200fcb
https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108
https://medium.freecodecamp.org/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b
