### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by dlrandy** [dlrandy/note-issues#52]
如何使得scrollbar总是显示的？https://stackoverflow.com/questions/1202425/making-the-main-scrollbar-always-visible
1：html {height: 100%} body{min-height:101%;}
2：html{height: 101%;}
3:元素的overflow设置成scroll，架上下面的这一段
``` css
::-webkit-scrollbar {
  -webkit-appearance: none;
  width: 7px;
}
::-webkit-scrollbar-thumb {
  border-radius: 4px;
  background-color: rgba(0, 0, 0, .5);
  -webkit-box-shadow: 0 0 1px rgba(255, 255, 255, .5);
}
```
