### ISSUE TITLE
HTML video iframe

### ISSUE THREAD

**Issue by dlrandy** [dlrandy/note-issues#62]
iframe
他是一个允许在网页里嵌入另一个网页(可以自己网站也可以是外部网站，还可以是文本pdf之类的， flash的话可能还需要其他的tag )的对象 

```html
<iframe src="https://www.findertoday.com/address-finder/address/Bhagatpur+Tea+Garden-9953?width=500&access_method=findertoday" target="_parent" width="500" height="270" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>


<iframe id="FileFrame" src="about:blank">
<html><body>test</body></html>
</iframe>

```

iframe不允许外部的css，js对其内部进行控制. 但是可以通过message进行通信

window.frames 虽然返回当前的window，但是它会有一个类数组，里面是直接的子iframe

```
window.frames[0] === document.getElementsByTagName('iframe')[0].contentWindow

var frames = window.frames;
for (var i = 0; i < frames.length; i++) {
    frames[i].document.body.style.background = 'red';
}

```

**Comment by dlrandy** [comment]
如何判断一个页面加载在浏览器的window里还是加载在iframe里？
1、使用window.frameElement
如果不是是iframe加载的他应该是 null的
2、
```javascript

function inIframe () {
  try {
   return window.self !== window.top;
  }catch(e) {
  // ie bug
  return true
}

}
```













常识
XSS
XSS攻击通常指的是通过利用网页开发时留下的漏洞，通过巧妙的方法注入恶意指令代码到网页，使用户加载并执行攻击者恶意制造的网页程序。 这些恶意网页程序通常是JavaScript，但实际上也可以包括Java，VBScript，ActiveX，Flash或者甚至是普通的HTML。
一般就是跨站脚本。
因为XSS，不同源下 iframe 里的parent是不允许访问location的

**Comment by dlrandy** [comment]
**由于浏览器同源策略的限制，不同源之间的属性和操作是无法直接交互的。**


跨域问题涉及的地方很多
文档间的消息传递，ajax请求，cookie等

**Comment by dlrandy** [comment]
对于全屏的元素使用伪元素添加样式

**Comment by dlrandy** [comment]
https://www.antidote.me/

把一个外部网站的页面潜入自己的网页中有两宗方式：
1、使用iframe
2、提供一个注入标记的script标记

iframe的优点：
1、嵌入外面的网站是比较安全的，iframe里的js运行在自己的浏览器环境的
2、不会阻塞渲染，iframe的页面和父页面同时加载
3、主页的js错误不会阻塞iframe的加载
4、易于更新和版本化
iframe的缺点：
1、并行
iframe的内容和main页面的并行加载。iframe会阻塞onload事件，要等到所有的iframe的内容资源加载完毕后，才会触发。 **解决的办法是通过js动态的设置iframe的src会解决这种阻塞。**
2、连接池
还有iframes和mainpage使用是同一个连接池。因为浏览器并行的连接有限，所以会阻塞mainpage的内容加载. 同样解决的办法就是在较高优先级的资源加载完毕后通过js动态添加iframe的src
3、不是响应式的
iframe完全不是响应式的，必须给它提供宽和高度
4、communication 
经常需要给iframe一些设置，可以使用postMessage
5、渲染iframe要比普通的DOM更耗费资源
js注入的方法 代码会把标记潜入到主页面里
好处：
1、灵活，可以直接访问js逻辑
2、可以自定义样式
3、没有布局的问题
坏处：
1、css和js容易冲突
2、难于更新
3、外部的js文件应该通过https提供

**Comment by dlrandy** [comment]
在web开发中一个widget是一个小UI 传递一些额外的功能和信息的。这个通常是别的公司的一个产品，是会潜入到我们自己的网站的。


http://rachelmccollin.co.uk/blog/responsive-iframes/

对于视频的处理，自己的博克网站可以把视频上传到别人家的server上然后引用。

潜入视频的两种方式：
1、video, 旧的IE 不好使
2、flash IOS上不好使

常识
padding margin的百分比是相对于包含块的的宽度。border的百分比不支持。
height的百分比相对的是包含块的高度
iframe的 响应式 ( 要注意它的长宽比)，这个也可以用到其它的元素上的响应上，比如img
步骤就是
1、先把iframe放到一个div.video-container里
```CSS
.video-container {
    position: relative;
    padding-bottom: 56.25%;//相对于包含块的宽度（16：9）75%(4:3) 由于相对的不同，使用height的百分比就不好使了，因为无法保证长宽比 
    padding-top: 35px;
    height: 0;//padding-bottom会有高度
    overflow: hidden;
}
.video-container iframe {
     position: absolute;
     top: 0;
     left: 0;
     width: 100%;
     height: 100%;
}

```


包含块
他是元素最近的块级 祖先的content area。
元素的size和position经常受到包含块的影响


识别包含块
这个完全取决于元素的position
1、position为static或者relative的时候，那么最近的祖先元素是块容器或者块格式化环境，具体是相对的content区域
2、如果position是absolute的，包含块就是最近的posiiton不为static的祖先元素，具体是相对于的padding区域
3、position是fixed的话，包含块就是viewport，具体就是page area，出现滚动条的话需要剪掉滚动条的宽度或者高度
4、position为absolute或者fixed的情况，包含块还可以是最近的有下面几个属性的元素:
   transform或者perspective不是none 的元素；
   will-change的值是tansform或者perspective的元素；
   filter的值不是none的元素；
第四项也就是告诉我们position:absolute/fixed相对的不仅仅relative影响

相对于包含块计算百分比的值：
1、height，top，bottom的百分比是相对于包含块的height。如果包含块的 高度依赖内容，且包含块的定位是relativeh或者static的情况，则这些值是0
2、width，left, right, paddding, margin是相对于包含块的width
上面的这些值计算，若是相对于content 区域的话，box-sizing为border-box的情况是没有影响的，但是视觉效果是不一样的.因为对于border-box他的宽高是包含padding的。
但是对于padding区域的，值的计算是不考虑padding的。

有一个思考：
对于border-box，若是上下padding的和正好是height的情况，height虽然有值，但是盒模型里height是0
的，也就是说padding也是可以撑起元素的高度的

块级元素就是独占一行的元素

块元素就是display为block的元素



这里有一个面试题就是why where height的百分比不生效呢？

**Comment by dlrandy** [comment]
BFC
块格式化环境会把里面的所有元素包含在创建它的元素里。

常见的可以形成以下情况：
root元素；
float不为none的；
绝对定位的absolute fixed;
inline-block;
overflow不是visible的；
table相关的；
flex;
其它。

clear清除float是让受影响的元素使用clear进行影响的 清除

BFC应用：
定位和清除浮动的原则只使用于在同一个格式化环境的情况。
margin折叠也只会发生在同一个块格式化环境中
多列布局。

浮动元素什么情况下会冲出父元素 ？
只要父元素没有形成快格式化环境的时候就不成哦

为什么float的元素周边会有文字环绕？
因为举例子当一个flaot元素后面跟一个满是文字的p元素时，p元素的line box会进行移动来填充浮动元素后面以及底下的空间。


https://bitsofco.de/how-floating-works/

实现多列布局有几种方式:
1、float
2、inline-block
3、position
4、flex
5、grid
6\table

**Comment by dlrandy** [comment]
来说以下响应式iframe的 原理吧？
首先就是需要一个relative定位的元素容器元素，包围 iframe，容器的元素取消height，使用padding-bot
tom撑起高度，设置成对应的长宽比。最后iframe绝对定位对正起始点，宽高设置成 100%


自动生成响应式的嵌入代码使用这个 http://embedresponsively.com/


使用css和js实现响应式Video的话，就需要使用js库了，比如fitVid.js, js的实现会有性能问题，所以尽量css实现吧


强制一个父元素自己清除孩子浮动的css 代码是用于IE8以上
```html
<style>
.group:after {
content: "";
display: table;
clear: both;
}
</style>
<div class="group">
  <div class="is-floated"></div>
  <div class="is-floated"></div>
  <div class="is-floated"></div>
</div>

```

**Comment by dlrandy** [comment]
iframe  video先听一停 

面试题一个：
如何实现一个元素的padding-bottom响应式的等于它的高度？
我的一个想法就是在requestAnimationFrame里动态计算宽高比然后反过来计算padding-bottom.



卷帘效果的实现:
两张图片 + 膜；
canvas/ svg;
filter;


https://stackoverflow.com/questions/11535392/how-to-decrease-image-brightness-in-css
https://www.html5rocks.com/en/tutorials/filters/understanding-css/
https://www.sitepoint.com/css-filter-effects-blur-grayscale-brightness-and-more-in-css/

https://developers.google.com/web/updates/2011/12/CSS-Filter-Effects-Landing-in-WebKit
https://iamvdo.me/en/blog/advanced-css-filters
https://www.sitepoint.com/create-stunning-image-effects-with-css-backdrop-filter/
http://kunkun12.com/MapSwipe//

https://caniuse.com/#search=backdrop-filter

**Comment by dlrandy** [comment]
display
inline:
1、没有margin-top/bottom
2、宽高的设置没有影响，它只是牢牢地包住内容，形成一个inline box
3、允许其它元素在旁边
block:
1、尊重margin设置
2、尊重宽高设置
3、独占一行
inline-block：
1、允许其它元素在旁边
2、尊重margin
3、尊重宽高

**Comment by dlrandy** [comment]
transform的translate的百分比是相对自身的
垂直居中可以用到的

阴影图片
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAI8AAAASCAYAAABim40OAAACuElEQVRogc1XUZJjIQjEzN7/yMl8ucP0dkNjXrKh6pWAqERaICveR+vD96vo8cazOvoYX54NwOl6Z52ycc907E4C4a45DfKrwHH5vpPgd7aTYKNOyUvYKL7zRZG6WNRP5cne7pxrMwHLEbCqS3aDMglwpcvjMmTGVz4wejQ86lDfjZ0OeSY/az/VMaJ2XQZA/QQQChSKV99N8OpjvuHvUsGt+ErX2bI9q7Hy0dE580pnZ0R1uTi/eSVX2SLrbmKeAeQG34qIL2KDozo/kwosBv4Ouk5WOheMyrfK5t1Z8K++Ak9XVjK/ZRW8LnMgYDZQtpx5lBFoERxI//z40EFmQLgn2R27PZkP0fDVGmaj5thdoE7JEREPBR6nFJ1+CCAFgq9mVF91dhUcBRgGHMWjju0TZN7xi+nVGmaH8wG2IeaUHH+ibyqRTuxZCVGyAhgrZQi0KrtlYgHYAV1JXvET8IjfF7jnb4mPpMtg2TZbr0rpSnwQO9SzjLAauxV83Zj2j1FU9QtX0fQMfD1VM6zWn9D00agz3fOr866OwRF1mUe9EmaDL8d9HflF5jS/M8Yd1rHzsWzt87HMdr0D+sB6HixPXV/EyqH6QvCqBOE9qPXMTsmMqI3TMG9eNc7P9EJYYvK/KdUsZz0raZF06Hu+DCxBD+BZv1L1RKeAcXsZpnNtgtiEmEOeyRHx0zBvchtnHBWAUFa66q86ggltuj5HZU73pVdAcMHhAEX5xHys/Ge/j43IO/IvfZdxmM4FVDdOs1X1Twr3YWciTYPjZopXZILOxgWElVGIjs5V/Yw752QrxU/A1fGdL4yciz551U45qILa+fbsOmeutekud2I7BeJJhmPr3L07KlN0Y/eMzpmb2JzYntgfXfIr9nLWXgl0RuPLO1xzxdqPOPNK8FxJn+rXhP4HON5K31PHDhmjlm6fAAAAAElFTkSuQmCC


```html
<div class="author__image-wrapper ">
	<div class="author__image">
	     <img src="https://www.gravatar.com/avatar/f99f27294a4a0acb07caa4d0604a1fef?s=500&amp;d=mm&amp;r=g" alt="Rachel McCollin">
	</div>
</div>
```
```css
img {
	max-width: 100%;
}
.author__image-wrapper {
			top: 0;
			left: 0;
			border-radius: 11px;
			overflow: visible;
			position: relative;
		}
		
		.author__image-wrapper::before{
			display: block;
			content: "";
			height: 90%;
			width: 160%;
			position: absolute;
			background-image: url(blur.png);
			background-size: 100% auto;
			background-repeat: no-repeat;
			top: 89%;
			left: -30%;
			right: 0;
			transition: all .1s ease-out;
			transform-origin: 30% 50%;
			pointer-events: none;
transform: scaleX(1.2);
		}
	.author__image-wrapper:hover::before {
			opacity: 0;
			transform: scaleX(0);
			transition-duration: .2s;
		}
.author__image {
			outline: 1px solid transparent;
			transform: translateX(15%) rotateZ(-11deg) scale(.87);
			transition: transform .6s ease-out;
			border-width: 8px;
			border-radius: 22px;
			background: #d33a2c;
			border: 5px solid #d33a2c;
			transform-origin: 0 100%;
			overflow: hidden;
		}
		
		.author__image:hover {
			transform: translateX(15%) rotateZ(0) scale(.87);
			transition-duration: .2s;
		}
		
		img {
			display: block;
			width: 100%;
			position: relative;
			border-radius: 11px;
			min-height: 50px;
			transition: transform .6s ease-out;
			transform-origin: 0 100%;
			transform: scale(1.2) translateX(-16%) translateY(-3%) rotateZ(11deg);
		}
		
		.author__image:hover img {
			transform: scale(1.2) translateX(-10%) translateY(6%) rotateZ(0);
			transition-duration: .2s;
		}



```

使用transform为什么产生锯齿？怎么解决？
主要 是因为元素是在非整数边界进行的渲染，也就是说width和height应该是整数。
也就是需要注意的是使用了transform的元素width和height最好是整数，
transform会产生多种影响:
1、对于边界的blurry，可以使用：
  outline: 1px solid transparent;或者backface-visibility: hidden;
2、对于字体的情况可以使用：
filter: blur(0);或者font-smoothing: subpixel-antialiased;
实在不行可以把scale换成zoom;
3、对于文本的 模糊， 要把元素的width和height要设置成偶数
