### ISSUE TITLE
css babel-regenerator

### ISSUE THREAD

**Issue by dlrandy** [dlrandy/note-issues#83]
offsetHeight 是包含border的高度
clientHeight是border以内的高度，不包含scrollbar的
scrollHeight在没有scrollbar的情况下是等于offsetHeight, 否则会大于offsetHeight
scrollTop是滚上去的高度
上面的基础主要是为了js实现多行的ellipsis

单行文本的ellipsis的使用的是
```css
//注意不是inline element
.block-with-text {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```

比较好的方案 ：
